dist: bionic
os: linux
language: shell
branches:
  only:
    - master
env:
  global:
    - IMAGE_NAME="orbnedron/jackett"
git:
  depth: false
services:
  - docker
notifications:
  email:
    recipients:
      - orbnedron@nordenbro.com
    on_success: change
    on_failure: always

before_install:
  - sudo apt-get install -y jq > /dev/null

before_script:
  - docker pull $IMAGE_NAME > /dev/null
  - export JACKETT_VERSION="$(curl -sX GET "https://api.github.com/repos/Jackett/Jackett/releases/latest" | jq -r .tag_name)"
script:
  - docker build --build-arg JACKETT_VERSION=${JACKETT_VERSION} --pull --cache-from $IMAGE_NAME --tag $IMAGE_NAME .
  - docker run --name jackett -d -p 9117:9117 ${IMAGE_NAME}
  - sleep 20
  - docker logs jackett
  - curl --retry 20 --retry-connrefused --retry-delay 3 -s http://localhost:9117 >/dev/null 2>&1
  - docker stop jackett
  - docker rm -f jackett
  - docker tag $IMAGE_NAME:latest ${IMAGE_NAME}:${JACKETT_VERSION}
  - docker images

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
