---
version: "3.8"
services:
  jackett:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JACKETT_VERSION=v0.16.722
    container_name: "jackett"
    volumes:
        - './data/config:/config'
        - './data/downloads:/media/downloads'
    ports:
        - 9117:9117
    restart: 'unless-stopped'
#    environment:
#      - JACKETT_USER_ID=123
#      - JACKETT_GROUP_ID=100

